[package]
name = "wstd-axum"
description = "Support for axum as a wasi http server via wstd"
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
tower-service.workspace = true
wstd = { workspace = true, features = ["json"] }
wstd-axum-macro.workspace = true

[features]
default = ["p2"]
p2 = ["wstd/p2"]
p3 = ["wstd/p3"]

[dev-dependencies]
anyhow.workspace = true
futures-concurrency.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_qs.workspace = true
axum = { workspace = true, features = ["query", "json", "macros"] }

[[example]]
name = "hello_world"
required-features = ["p2"]

[[example]]
name = "hello_world_nomacro"
required-features = ["p2"]

[[example]]
name = "weather"
required-features = ["p2"]
